### ISSUE TITLE
Can't paste template... Template includes scenery which is unavailable

### ISSUE THREAD

**Issue by guillaumecardon** [Sadret/openrct2-scenery-manager#10]
Hello,
I try your plugin on a classic scenario (Crazy Castle).
I selected an area and when i click on "Copy area", i've got the message "Can't paste template... Template includes scenery which is unavailable"

I changed behavior in this case to "ignore", but i don't understand the error

![image](https://user-images.githubusercontent.com/47170797/104819822-6fa9b700-5830-11eb-8cdb-9847c426f527.png)

OpenRCT2 v.0.3.2-397

**Comment by Sadret** [comment]
This reminds me of an issue that I had with an earlier version.
Can you confirm the behaviour with the current release without any other plugins active?
