### ISSUE TITLE
Colourable Large Scenery is not copied correctly

### ISSUE THREAD

**Issue by danielmeinert** [Sadret/openrct2-scenery-manager#11]
When copying a LS object that is colourable the colorinformation is not copied and the object is just placed with it's colors set to black.

**Comment by danielmeinert** [comment]
addendum: also colourable walls are not copied properly with the right color

**Comment by Sadret** [comment]
Caused by: https://github.com/OpenRCT2/OpenRCT2/pull/13651
Already fixed in 3535d36d and will be released with v1.1.5.
