### ISSUE TITLE
Feature Suggestion: toggle option for the area selection tool and placing scenery cursor

### ISSUE THREAD

**Issue by danielmeinert** [Sadret/openrct2-scenery-manager#12]
At the moment when selecting the area to copy and when placing the scenery the position on the map grid is determined by the scenery object the cursor focuses on. I understand that in some cases this might be very useful (especially at the selection process of tall buildings). In other occasions it is hindering the process a lot, when the area you are working on is quite full of objects already for example and you want to copy some area precisely. Also for placing objects I think it is not very useful for the same reasons, sometimes it is even impossible to get something into the right position. 

So I would suggest an option to toggle this tile selection, so either the tile is targeted where the cursor points to, regardless of which object is in line (like it is the standard in RCT2 with objects, landtool etc., or the object hovering is activated. A hotkey toggle like in the tile inspector with ctrl would be the prime solution, but I think a checkbox toggle in the options would work, too.

**Comment by Sadret** [comment]
This is not possible with the current API, as it only provides the coordinates of the tile on which the object under the cursor is.

**Comment by danielmeinert** [comment]
Then maybe as a workaround some buttons in the tool to increase/decrease the size of the selection box in x and y might do the trick? I mean atleast for the selection tool. 

for scenery placing it might get a little more messy, sadly

**Comment by Sadret** [comment]
I will include it in my to-do-list, but it wont be top priority right now.
