### ISSUE TITLE
Feature suggestion: Height limits in selection

### ISSUE THREAD

**Issue by danielmeinert** [Sadret/openrct2-scenery-manager#17]
At the moment all scenery (and other stuff) on a selected tile is copied. I propose a lower and upper height limit, which indicates a window in the z axis from which the scenery will be copied. This would be very handy when copying only parts from architecture for example when you want to move/duplicate just the roof and not everything below.

**Comment by Sadret** [comment]
Implemented with 7613830225dbd345b8e95da83228ddf068ecdbfe
It still copies everything, as there is no way to give a visual feedback about vertical bounds.
Pasting can now be restricted to a vertical window.
