### ISSUE TITLE
Respect Z/Y default rotation shortcuts

### ISSUE THREAD

**Issue by Richard-L** [Sadret/openrct2-scenery-manager#2]
First of, I'm still speechless as to what huge of an achievement this is, WOW! It feels like such a seminal moment in the RCT community to have this plugin. Thank you again and again.

One quick reaction upon first use: would you be interested in incorporating keyboard shortcuts, such as for instance the Z/Y keys (depending on region), as these have been the default for "rotate object" since RCT1 days.

Really just a usability enhancement suggestion of course.

**Comment by Sadret** [comment]
Thanks for your feedback!
Would I be interested? Yes.
Is it possible right now? No.
Do I plan to make it possible? Yes.

**Comment by Sadret** [comment]
Hotkeys are now implemented and will come with version 1.2.0 .
