### ISSUE TITLE
Brush tool controls bugged

### ISSUE THREAD

**Issue by danielmeinert** [Sadret/openrct2-scenery-manager#20]
After selecting the 6th object to the brush tool, the button for 'Add' stays in the clicked visual state. It still works. Also the size selection becomes faded.

After selecting the 7th object, the -10% button of the 7th entry shows the permantly clicked behaviour. Now the activation button is faded and doesnt work

From now when adding new objects to the selection, two rows of faded object entries travel through the selection, where you cannont control the percentage of one.

**Comment by Sadret** [comment]
Apparently only 64 widgets per window are allowed. After hitting the limit, it messes with disabling / enabling.

**Comment by Sadret** [comment]
https://github.com/OpenRCT2/OpenRCT2/issues/14235

**Comment by Sadret** [comment]
I implemented a workaround where the number of objects is now limited to 5.
It will be included in version 1.2.0 .
