### ISSUE TITLE
Feature Suggestion: Height Adaptation

### ISSUE THREAD

**Issue by cogthecat** [Sadret/openrct2-scenery-manager#21]
When copying and pasting (primarily scatter scenery, but I can imagine this being useful in other use cases), it seems like it would be very helpful to have an option for pasted scenery to attach to whatever height the surface below it is as though it were placed manually without using the virtual floor. The specific way I have in mind is to take complex scattered terrain, or manually-placed objects from one surface to any surface with differing geometry with all of the tile objects "snapping" to the surface above or below.

As it works right now, the copied objects always keep the height they were originally placed at (more useful for copying buildings etc.) instead of snapping (more useful for copying gardens or forests consisting of only aboveground trees).

**Comment by Sadret** [comment]
Interacting with foliage on sloped surfaces is quiet difficult and not fully supported right now.
See e.g. Copy/Paste which does not work very good in hilly terrain.

Right now, I do not see a way to implement this feature without dropping ghost placement. Maybe in the future an API improvement can change this.

**Comment by cogthecat** [comment]
Quite understandable. In the use-case I described I would readily prefer
toggling ghost objects off and being able to copy with height-adaptive
object placement, but I imagine there are plenty of reasons that wouldn't
be a desirable feature to add.

**Comment by Sadret** [comment]
Fixed in 7613830225dbd345b8e95da83228ddf068ecdbfe

**Comment by Sadret** [comment]
Confused this issue with #21 ...
