### ISSUE TITLE
Issues with copying paths In new .Park save format

### ISSUE THREAD

**Issue by sumtheparts** [Sadret/openrct2-scenery-manager#24]
Trying to copy any tile that contains one of the new path items from the .Park test fails to copy any items, even when filtering to remove footpaths. 

I have no idea if you plan on updating the plugin for the new file format, but I just thought I should bring the issue to your attention.

So far all other functionality seems to still work in the test build.

**Comment by Sadret** [comment]
Yes, I will update, but it may take some time.

**Comment by Sadret** [comment]
Solved with 609943e203df830951fd6fee704d9678eaedf57b
