### ISSUE TITLE
Brush tool doesn't close when the plugin window is closed

### ISSUE THREAD

**Issue by fidwell** [Sadret/openrct2-scenery-manager#26]
If you open the scenery plugin, select a range of objects (so you get the brush tool activated), then close the plugin window, the paste brush tool does not deactivate. You'll still see the rectangular selection area and ghost scenery. It no longer does anything when you click, but it is an annoying visual glitch. You can clear it by activating a different built-in tool (like the landscaping tool).

**Comment by Sadret** [comment]
Not a glitch, but intended behaviour. But one could argue that it should be different.
Anyway, you can always press ESC to cancel your tool.

**Comment by fidwell** [comment]
Yeah I would argue that it should be different :p  I guess it's personal preference, but none of the built-in tools in the game work the same way. To me, it's expected that when I close the plugin window, it means I'm done with the tool and ready to do something else, so having the brush still be active is a distraction and can cause accidental scenery placement.
