### ISSUE TITLE
Gridlines

### ISSUE THREAD

**Issue by Richard-L** [Sadret/openrct2-scenery-manager#3]
Struggling to reproduce this one properly, but in some occasions, the plugin seems to override the "gridlines" setting in ORCT2. They will just disappear despite showing as turned on:

![image](https://user-images.githubusercontent.com/4934209/101219857-f3df1b00-3684-11eb-99cc-196133e14eec.png)

**Comment by Sadret** [comment]
I can reproduce that. I have an idea for a workaround, which is not quite as good as a fix though.

**Comment by Sadret** [comment]
Actually this is issue https://github.com/OpenRCT2/OpenRCT2/issues/13372.
