### ISSUE TITLE
Jump to Road objects in BPB spams JS errors

### ISSUE THREAD

**Issue by Basssiiie** [Sadret/openrct2-scenery-manager#31]
Jumping to `Road` objects in Blackpool Pleasure Beach (the one from the RCT1 import in OpenRCT2) does not work consistently and seems to spam errors in the plugin. Also the 'searching...' that is seen in the window never finishes its searching.

See screenshot:
![image](https://user-images.githubusercontent.com/20048660/172009279-846d9121-3c3b-4bd9-963d-84e215574dc4.png)

The errors that are spammed:
```
[scenery-manager] Cannot read 'ride' property, path is not a queue.
[scenery-manager] Cannot read 'station' property, path is not a queue.
```

**Comment by Sadret** [comment]
The errors are a known issue, they are not easily surpressible. But they are actually only warnings, so it's fine.
For the search/jump issue, I would need to have the save file to investigate the issue.

**Comment by Basssiiie** [comment]
@Sadret It's the BPB imported from RCT1, I didn't do anything else in this park. But if you haven't got RCT1, here's a save of it anyway. :)
[Blackpool Pleasure Beach.zip](https://github.com/Sadret/openrct2-scenery-manager/files/9034618/Blackpool.Pleasure.Beach.zip)
