### ISSUE TITLE
Plants and trees not selectable

### ISSUE THREAD

**Issue by workermaster** [Sadret/openrct2-scenery-manager#32]
I have installed the plugin on a dedicated OpenRCT2 server running in a Docker container on Unraid. I can use the plugin to place benches and other things, but mainly wanted it for the ability to have it place plants. 

The plants screen is not working and I can't select plants. This is what I can see on the plants tab:
![image](https://user-images.githubusercontent.com/80215615/174112819-812616fc-558c-4932-b29f-d5799e7c02d8.png)

The button "Pick" doesn't do anything, but it also doesn't work on other tabs. I don't see a way to select what plants I want.

**Comment by Sadret** [comment]
Can you tell me what the output of the RCT console is? Especially while loading the map, opening the Scenery Manager window, selecting the Scatter tab and clicking the Pick button.

**Comment by workermaster** [comment]
I am running a headless server and am not sure how to open the console. I have only found one console and that is this one:
![image](https://user-images.githubusercontent.com/80215615/174299089-c6e345a0-2e25-4370-b282-ddf36c666daa.png)

Is that the correct console? It never shows any text about what is happening in the park. But I can type some commands in there

**Comment by Sadret** [comment]
I think this is the legacy console, but I'm not sure, I never use that one.

Since you are using a headless server, I guess you start a local client and connect with it to the server. Do not start the client via the exe (or whatever it is on your platform), but instead run the openrct2.com file. It will start the game and show you the console.

Also note that spam protection will immediately kick in if you place more than a handful of scenery pieces. You will note this by the "please slow down" message.

**Comment by workermaster** [comment]
I just found out how to use it. I expected a popup list when I click on the "Pick" button, but you have to select a tree on the map. Sorry, I feel like an idiot. 

I did notice that my mouse turned into a cross and I couldn't click on anything anymore. I thought that was the plugin being broken, and didn't realise that I had to select a tree. 

I am getting the slow down message, but that is not a problem for me. I will just place them slower, or less at a time. It works perfectly in single player.

**Comment by Sadret** [comment]
Glad you found it out. As a general theme, "Pick" means "pick from map" while "Select" means "select from list".
