### ISSUE TITLE
Fence slope is not persisted when copy/pasting

### ISSUE THREAD

**Issue by fidwell** [Sadret/openrct2-scenery-manager#33]
If I have any fences with set slopes, and copy-paste some scenery, the slope of the fences is not carried over and they will all be flat.

See in this screenshot how many of the the wooden post fences on the left are sloped, but in the paste preview on the right, they are flat.

![image](https://user-images.githubusercontent.com/5436387/177047258-181817f4-9d08-4674-8939-b0b26e2e229e.png)

**Comment by Sadret** [comment]
Use raw mode.
