### ISSUE TITLE
Scenery manager places the wrong scenery

### ISSUE THREAD

**Issue by Lucius6** [Sadret/openrct2-scenery-manager#38]
I tried to get this pattern going:

![Schermafbeelding 2023-06-24 171115](https://github.com/Sadret/openrct2-scenery-manager/assets/49132759/ae9fda41-ee11-4e69-b2ea-9ee266378181)

But this is the result, it places items I didn't ask:

![Schermafbeelding 2023-06-24 171150](https://github.com/Sadret/openrct2-scenery-manager/assets/49132759/6ad8c836-0bc1-44fa-a6f6-b9edf1f12d19)

I'm playing on the latest dev build

**Comment by Sadret** [comment]
Caused by https://github.com/OpenRCT2/OpenRCT2/pull/20177

**Comment by Sadret** [comment]
Fixed in https://github.com/Sadret/openrct2-scenery-manager/releases/tag/v2.0.2

**Comment by Lucius6** [comment]
Thanks for solving this so quickly.

**Comment by Sadret** [comment]
No problem, it also affected Copy&Paste, so it was quite important. Thanks for notifying me!
