### ISSUE TITLE
Doesn't recongnize scenery or buttons don't work annymore

### ISSUE THREAD

**Issue by Lucius6** [Sadret/openrct2-scenery-manager#40]
Just updated the game to the latest dev build. Now the scenery manager doesn't recognieze scenery annymore. 

As you can see, it's says 0 for everything. Pressing scan doesn't work.

![image](https://github.com/Sadret/openrct2-scenery-manager/assets/49132759/8d9e5cd3-5391-422d-abdc-54434e7a7283)

Also for managing foothpaths, picking an item also does nothing, like any button that let's you pick something.

**Comment by Sadret** [comment]
Possibly caused by https://github.com/OpenRCT2/OpenRCT2/pull/20480

**Comment by Lucius6** [comment]
There is a new dev build out and now it works again.
