### ISSUE TITLE
Selection kept when tool is closed by hotkey

### ISSUE THREAD

**Issue by guillaumecardon** [Sadret/openrct2-scenery-manager#46]
To reproduce the bug : 
- Open Scenery Manager
- Click on "Select"
- Select an area
- Click on "Copy" (or Cut)
- Close the tool with the game hotkey (backspace key by default)
- Tool is closed, but selection is always present.

To remove the selection, you need to re-open Scenery Manager, click on "Select".

(Obviously, option "Keep selection when finished" is unchecked )

**Comment by Sadret** [comment]
I think there is a misunderstanding here. When you press backspace, you only close the window, but you do not cancel the tool.
Scenery Manager is designed to work with hotkeys and most players do not have the window open while using it. This means that it is intended behaviour that the tool is still active even if you close the window.
If you want to cancel the tool instead, press escape.
