### ISSUE TITLE
Crash when copying walls after using Fidwell's Shift Map plugin

### ISSUE THREAD

**Issue by astraylife1** [Sadret/openrct2-scenery-manager#47]
I used Tidwell's shift map plugin to shrink a large map and shift it over quite a bit. Now when I use scenery manager for this particular park, the game will crash any time I copy a wall and move the cursor outside of the scenery manager window. I am having trouble replicating this particular issue on other parks after shifting the map so I'm not sure exactly what is happening. Github won't let me attach the park file so here is a link to the affected park file:
https://drive.google.com/drive/folders/1lQlMtktZawD5G4N2LiRPh0m1vKuhuDSD?usp=share_link

**Comment by Sadret** [comment]
Hi, thanks for the report. Your Google Drive file is not accessible, can you please make it open to the public?

**Comment by astraylife1** [comment]
Oops, forgot to unrestrict it:
https://drive.google.com/drive/folders/1lQlMtktZawD5G4N2LiRPh0m1vKuhuDSD?usp=share_link

**Comment by Sadret** [comment]
I can reproduce the crash, but it is not a bug within the Scenery Manager plugin.

**Comment by Sadret** [comment]
Safe mode is still working btw.

**Comment by astraylife1** [comment]
Thanks for checking!

**Comment by Sadret** [comment]
Fixed in https://github.com/OpenRCT2/OpenRCT2/pull/22674
