### ISSUE TITLE
Ghost objects form when dragging a template over water.

### ISSUE THREAD

**Issue by thiebert** [Sadret/openrct2-scenery-manager#5]
https://cdn.discordapp.com/attachments/234774211330048012/784549583614509066/unknown.png

To produce this, I copied a template with objects on a slope, then dragged it over water. I had sandbox mode enabled, but no other cheats that I think would be relevant.

**Comment by Sadret** [comment]
Cannot reproduce. Does it maybe depend on a custom object? Is it reproducable with a vanilla object?

**Comment by thiebert** [comment]
This was on a vanilla scenario with all vanilla objects. I'll try to get better reproduction steps.

**Comment by thiebert** [comment]
On Botany Breakers, selecting and copying a large area towards the center of the map where there's lots of elevation difference, then dragging that selection over the water near the park boundaries seems to make this pretty commonly reproducible

**Comment by Sadret** [comment]
I'll look into it.
