### ISSUE TITLE
Plugin doesnt work in the Scenario Editor

### ISSUE THREAD

**Issue by Spearkiller** [Sadret/openrct2-scenery-manager#7]
I was building a scenario, and since it is an "urban" based one it required building a lot of terraced houses and all that, Not wanting to do it by hand, thankfully I found this plugin. Unfortunately, it doesnt seem to work in the Scenario Creator, as you can see here:
![image](https://user-images.githubusercontent.com/10781437/101296663-80f2c180-3889-11eb-8011-b1e1444b07b1.png)

But when I open a normal scenario it works fine
![image](https://user-images.githubusercontent.com/10781437/101296661-7a644a00-3889-11eb-86eb-d5720bf377ef.png)
I didnt even get the "thank you for installing" popup until I opened a regular scenario.

I dont know if this is a bug, oversight, or limitation, or just me missing something, but it would be really handy if this could be looked into, thanks :)

**Comment by Sadret** [comment]
This is a general limitation of the plug-in system of OpenRCT2 and not an issue of this plug-in in particular.
