### ISSUE TITLE
Allow sampling objects placed with "Zero clearances" enabled

### ISSUE THREAD

**Issue by Richard-L** [Sadret/openrct2-scenery-manager#8]
Currently, unless zero clearancing is enabled, it's impossible to sample scenery which was placed whilst ZC was active. The same goes for placing it, too.

Is it possible to skip that step and have it always sample and place all objects, regardless of whether ZC is active or not?

Many thanks.

**Comment by Sadret** [comment]
This is intended behaviour and I do not plan to change that.
Right now, the plug-in interacts with the world only through so-called game actions, which is my preferred way and the best practice in my opinion. Changing this would mean a huge re-do of already working code.
You can always disable ZC yourself though.
