### ISSUE TITLE
Plugin non-functional on OpenRCT2 for Mac

### ISSUE THREAD

**Issue by danpaquette** [Sadret/openrct2-scenery-manager#9]
Did not receive welcome message and the plugin does not appear in in the menu. Tried loading a game, starting a new game, and the scenario editor.

https://imgur.com/a/ZY7T8MM

OpenRCT2 v0.3.2
MacOS Catalina

Let me know if I can provide any further details to help hunt this down.

Thanks!

**Comment by Sadret** [comment]
Please make sure to have a _development_ version installed. The plug-in API of the v0.3.2 release is not sufficient for this plug-in.
